apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "hello.example.com/v1alpha1",
          "kind": "Helloworld",
          "metadata": {
            "name": "example-helloworld"
          },
          "spec": {
            "hello": "world",
            "size": 3
          }
        },
        {
          "apiVersion": "hello.example.com/v1alpha1",
          "kind": "Heyyou",
          "metadata": {
            "name": "you-heyyou"
          },
          "spec": {
            "hey": "you",
            "size": 3
          }
        }
      ]
    capabilities: Basic Install
    certified: "false"
    containerImage: quay.io/sbergste/helloword-operator:v0.0.1
    description: Simple Ansible Operator just for testing and learning
    repository: https://github.com/stefan-bergstein/helloworld-operator
    support: sbergste@redhat.com
    createdAt: 2020-06-13T20:00:00Z
  name: helloworld-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Helloworld
      displayName: Helloworld
      name: helloworlds.hello.example.com
      description: Helloworld CRD
      version: v1alpha1
    - kind: Heyyou
      displayName: Heyyou
      name: heyyous.hello.example.com
      description: Heyyou CRD
      version: v1alpha1
  description: Simple Ansible Operator just for testing and learning
  displayName: Hello World Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAALQAAAC0CAYAAAA9zQYyAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAG66AABuugHW3rEXAAAAB3RJTUUH5AYLDDII8/GksgAAC2xJREFUeNrtnV9ol9cZx791bjqSbmsxUQumSTSWsKQZKrpRIvtDO22xWak3jdILZb0Y2GF2sy3CIqsbFKa0F/NiMCPxathRCiozmoU6thpsqeCSllZILdr5p9WsKTFNa3bxO842JL/ned/z5z3v+/t+4L3J+/ud5znP8835nfe85w9ACCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYREz10MgRMeALAcwAoASwHUAbgHwL1zfP4jANcBXADwAYB3AZwH8DZDSUGHZg2A9QC+D+A7AJY5Lv99AG8CGATwKoAzDDlxSS2AXwI4BWA6o+uU8aGW6SBpRdwD4HKGIp7rumx8o7iJyJMATkco4rmu08ZnQr7EbgATORLyzGvC1IFUOHtzLOK5rr1Ma+Wxq4BCnnntYpqLzwYANxwL5w0A4w7KGTdlufTthqkzKRhVAAYcieQ4gGcBrDRlP+VQgE+ZMlcaG8cdlTtgYkAKQKelGKYA9AJ4aJaylyjL6DOX5rNLZrHzkPFhyrIunZRDvjlqkfy/A3hcKH9UKOMWgJEvfH7E/K3cd0YFm48b39LW6yhlkT/qAYylTPifUJqPIdGjKOvmjJ/6KvM36Xs9CvtLja9p6jhmYkRywOaUSX4RwAKljQZlmetm+e465XcblL4sML6nqXMH5RI3PSmS+lcANQntnFOUu6fM9/covn8uoU81pi5J699D2cRJX8JE/gdAWwo72xVlDyvKGVaUsz2Ff22mbkli0Uf5xMWxhAn8TUo78yxGKtKOkMwL9Gt1jDLKn5jHADRb2DqosLEzQXk7FeUdtPC3OeHDMUWdIzH3W9qq89Dv1fbH6yx976eoi9Vn7nZg74TCTmOKchsV5Z5w4H83+9TFGM3Y6MDeWoWd/Rbl71eUv9ZBPTZy9CM+OhIkpcWRzSGFLVuk8occ1aUFHKeOhvoEyWh1ZFPTOu9wYGdHoFYaJjbaONZTdv4YCyxmzQPVVYe2rnp+sE0j6jHKzg/aiUYtDm0uV9jb4tDeFoW95Q7tabsfnNDkGO0U0E2O7R4I2DprW+kDju1tAqeeBqUqo6fy+QqbWz3Ud6vC7vyMRo24SMABmpUmgx7sdgk2Jz3WeVKw3eXB5iB0K1+IBRugWzfng4sZiEr7z3TRk13NekuuUfQc4DYPdlfB/7izhGR/lQebbRk2IIVHs9WArz0oepH9q2Hp1X6vJ7uavUq4RYKHFupahrZbA9RfM07si2sR/EIVin2KgLZ7sv1oRv3XNP34Rz3ZbVfEfx9l6q6FPJnhT313wDhIM+R8dn1OspV2w25FIBd5tC/tfXFPwFjUQt4zxBeLFHngBpEKpF1AD3m0vQb2awVdI609XOPR9iHIu55GxfzI/HkSwELhM4cBfNeT/W3C/X+htA1BqKM8po3NcsvGnvGYx8MoP1dlocnZS2yHZydPm43zurPpejTEdGhQLUrHLZD8sRjAlRgcmRdRUH5GXeSWaHIXUwt9GTwIJ69cMa00W+gvdDco5vwSTf5iEfQ2aiL3bKOg7/AY9ZB7oshhLH1o6TVqB4BveLS/BsDPy9z/M0qbjGfJD4RW8AX4PUZ5AqVx6bw8k2WG9HbuSAAfpDkT7RHESZowFGKOycvI7q1lbroc64X7fwvgw2rh/msRxOk1yzq44IhlLiuCV4T/+pUBfCg3X+LTiGL1KbKdZyLtw/cK5QxcQPZTFMstSj0bUazOIptFuzOfd+a6LrDLASwrc+/1QD58TWi9Y2E4ZR1ccjplLitC0A9YBM8V0m7770Uk6Pcs6+KC1y1zWmhBS9tanQvgQ0OBBN0QwId/W+a00IJeIdw/H8AH6ZXtpYgEfcmyLi4YscxpoQUtLaV6J4AP1cL9mKa0XrasiwuknCytZEFLP08hWsdlBRJ0iIcyKSd1lSxoacFpiKEoacnXxxEJ+mPLurjglmVOCy3oezMWs4aY5ifE4st4ypwWXtBpg+aSz4X7VyOKyVXLurhiMlbRxCzoUDSzLsWBgiYUdMEYYV0o6BBUB7LzFeF+TUQxqbGsiysWUNCz81EOghbTpoSx+FKdMqeFF/T1CFqCm8L9uyMS9N2WdQmhmeuVLGhp/ux9AXx4X7i/OCJBL7asiwuknJyvZEF/INxvCuDDeIEEHWLsXsrJtUoW9LvC/RBTEaWXFXl6KAzxEqjZMqeFFrT089QSwIe3hfv3RyTo+y3r4oJvs8uRPgHrAvjwYQTdHlc/9x8G8GF1BP9UURPDItlyq6nzskg21Op0LpIVeFO4H2IbgxGLPmNImlPWwRWNlrmsCEEPCvdDHMX7Vpl7XzVX1kh+vBXAhx9Z5rIiBP2qcP/HAXyQVjKvjiBOqy3r4ILHLHPpnTxs1jgNYCf8roRoQenwm7l4OYK+dBuAn5S5/xL8rpKfBPCc0Ahys0bDKfDwnbxfp2IQUiyz7Y7wfzr3RJHDWH4ieAJW/oniJKxYWugriORYMJLv/MU0wX8/dZFboskdD94kheluxNZCXwEwJHxmmtoJjhTzoZi6i7EdXv88yh9McxdKs72ueErcrwF0lfnM7wH8AWEPr/8FgF+V+cxeAL/z5FMt5N1Gn+f/fHkmUH6885BH29IBRmcyiMcZZHdQzyHB9gTlKrMb8iD+Io/2PxNsVweMRbXgy2cebS9S5GE35ar/qS13nfRo+4Bge1fAOOwSfDng0fZJRR6Ikn2KYPo6O/ARwe5owDiMCr484sluuyL++yhTt620z8WYU4LtBwPUv1XwYcqj7WtsncP/3E6bJ3wf9Gb4U3+bPsGHXk929yrivovyTMcNRXDbPNhdFUELJdlf5cFmm8LuDcoyPRsyDPBFwW6Xx3p3CbYvZtiAbKAs7RhQBHkwA1H53NRlMoN/pkFFnAcoR3uqoJtg3uPY7nyFzS0e6rtVYdf1G94eZYyrKEc3dCoDvsmxXWlM2sdORVcDP5BuUsa2kzJ0y1Fl4F3utlQXuJXeorDn8ti0FmVMj1J+fhhTJqDVoc3+gK201Dr3O7TVqozlGGXnj3roF226EvVaha1nHdjZobCzNrCYp03MiUc6EiTDVfdjCP4nCUl1GXJUl5YE8eug3MLQkyApGwO10jbLkPYHap03JohbD2UWlr4Eyel2YO+Ewk5jinIbFeWecOB/d4J49VFe2XAsQZJsH6g0Ix5pdi46F2Bkoz9BnI5RVvkR9RiAFRa2Dips7ExQ3k5FeQct/G2CbuYcxZxjUdv0D+cpy1+iKGuJsqy0C5l7EsaEYs5xn3oapROj0szU264oe1hRzrCinO0p/GszdUsSC/aZCzD6cfv6C5LPUdD0e/eU+f4eD/3xKlOXpPXnaEbkbEa63TNfhP6gzwZlmbOdEbNO+d0GpS8LjO9p6ryZcskH9dC/Jp95vQDdUW6aX4ObM1r/KvM3F61mjfE1TR3HwDeAuaQf6fc7Pg7gYaH8UaGMW/jy2Scj5m82i3AfNr6lrRcnGuWcp2G3kfcUgD9i9lXm2pGKvgQPrbONkLQbH6Ys6/I05VAMvgXdyhfNdRjAT3HnrWAn3O2Cf3vOcaOxcdhRuQMmBqRgPIHS0imXRzH8A8AnDsr5xJTl0rdxU2fC4b3cXxyOqzBshrtivpIMP5ICshCl48ryLuTnTF0I+T/PmKG1vIh4xPhMSFnqAfwWwPUIRXzZtMb1TBNJQ5N5wDqboYjPoDRBv4npKA+Psk3ODwGsB/A9lF54fN1x+f8FcBrAP1E6O5u7FVHQwWP4IEoLB5oA3AfgmwCaUXrNPRufAziP0l5ylwC8Y/rDt/vvhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIKS7/A6yMBFM6O58DAAAAAElFTkSuQmCC
    mediatype: "image/png"
  install:
    spec:
      deployments:
      - name: helloworld-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: helloworld-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: helloworld-operator
            spec:
              containers:
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: helloworld-operator
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: quay.io/sbergste/helloword-operator:v0.0.1
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 6789
                  initialDelaySeconds: 60
                  periodSeconds: 10
                name: helloworld-operator
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
              serviceAccountName: helloworld-operator
              volumes:
              - emptyDir: {}
                name: runner
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - helloworld-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - hello.example.com
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: helloworld-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - ansible
  - hello
  links:
  - name: Helloworld Repository
    url: https://github.com/stefan-bergstein/helloworld-operator
  maturity: alpha
  provider:
    name: Helloworld Community
  version: 0.0.1
