apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: helloworlds.hello.example.com
spec:
  group: hello.example.com
  names:
    kind: Helloworld
    listKind: HelloworldList
    plural: helloworlds
    singular: helloworld
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
#  versions:
#  - name: v1alpha1
#    schema:
#      openAPIV3Schema:
#        type: object
#        x-kubernetes-preserve-unknown-fields: true
#    served: true
#    storage: true
