---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: helloworld-operator
  template:
    metadata:
      labels:
        name: helloworld-operator
    spec:
      serviceAccountName: helloworld-operator
      containers:
        - name: helloworld-operator
          # Replace this with the built image name
          image: "quay.io/sbergste/helloword-operator:v0.0.1"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "helloworld-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
            # Azure config        
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: AZURE_CLIENT_ID
                  name: helloworld-operator-azure-conf
            - name: AZURE_SECRET
              valueFrom:
                secretKeyRef:
                  key: AZURE_SECRET
                  name: helloworld-operator-azure-conf
            - name: AZURE_SUBSCRIPTION_ID
              valueFrom:
                secretKeyRef:
                  key: AZURE_SUBSCRIPTION_ID
                  name: helloworld-operator-azure-conf
            - name: AZURE_TENANT
              valueFrom:
                secretKeyRef:
                  key: AZURE_TENANT
                  name: helloworld-operator-azure-conf
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 60
            periodSeconds: 10
      volumes:
        - name: runner
          emptyDir: {}
